# Generated by Django 6.0.6 on 2026-07-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('B', 'Nascimento'), ('W', 'Casamento'), ('D', 'Óbito')], default='B', max_length=1)),
                ('event_date', models.DateField(verbose_name='Data do evento')),
                ('event_location', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=300)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(verbose_name='Data de criação')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('C', 'Certidão'), ('P', 'Fotografia'), ('T', 'Tradução'), ('R', 'Registro Paroquial'), ('N', 'Censo'), ('I', 'Inventário')], default='C', max_length=1)),
                ('file', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='genealogy.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('F', 'Pai'), ('M', 'Mãe'), ('C', 'Criança'), ('G', 'Noivo'), ('B', 'Noiva'), ('P', 'Padre'), ('W', 'Testemunha')], default='F', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.person')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', through='genealogy.EventParticipant', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genealogy.tree'),
        ),
    ]
