# Generated by Django 6.0.6 on 2026-07-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
